<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Aplication Type' => '',
    'Are you sure you want to delete this item?' => '',
    'Business Name (If different from legal name)' => 'Nombre comercial (si es diferente al nombre legal)',
    'Business Title' => '',
    'Civic Address' => '',
    'Create News' => '',
    'Create Oadode' => '',
    'Delete' => '',
    'Description of Controlled goods' => '',
    'ECL Group No.' => '',
    'ECL Item No.' => '',
    'Email' => '',
    'Facsimile Number' => '',
    'ID' => '',
    'Lang' => '',
    'Language' => '',
    'Legal Name' => '',
    'Mailing Address (If different from civic address)' => '',
    'News' => '',
    'Oadodes' => '',
    'Oadote ID' => '',
    'Reset' => '',
    'Save' => 'Guardar',
    'Search' => '',
    'Telephone Number (Include extension no. if applicable)' => '',
    'The requested page does not exist.' => '',
    'Update' => '',
    'Update News: {name}' => '',
    'Update Oadode: {name}' => '',
    'Description of the controlled goods the applicant be required to examine, possess or transfer (Refer to the Export Control List (ECL))' => 'Descripción de las mercancías controladas que el solicitante debe examinar, poseer o transferir (consulte la Lista de control de exportaciones (ECL))'
];
